# Generated by Django 5.2.1 on 2025-06-12 11:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_employee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_currency', models.CharField(default='AZN', max_length=3)),
                ('initial_data', models.JSONField(default=dict, help_text='Initial salary data from Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading System',
                'verbose_name_plural': 'Grading Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10)),
                ('base_value', models.DecimalField(decimal_places=2, help_text='Base minimum value (Blue Collar LD)', max_digits=15)),
                ('grade_order', models.JSONField(default=list, help_text='Order of position groups')),
                ('input_rates', models.JSONField(default=dict, help_text='User input vertical and horizontal rates')),
                ('calculated_grades', models.JSONField(default=dict, help_text='Calculated salary grades')),
                ('calculation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('vertical_avg', models.DecimalField(decimal_places=4, default=0, help_text='Average vertical percentage as decimal', max_digits=5)),
                ('horizontal_avg', models.DecimalField(decimal_places=4, default=0, help_text='Average horizontal percentage as decimal', max_digits=5)),
                ('metrics', models.JSONField(default=dict, help_text='Basic calculated metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_scenarios', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='grading.gradingsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('changes_made', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_current_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.salaryscenario')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grading.salaryscenario')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_decile', models.DecimalField(decimal_places=2, help_text='LD - Lower Decile', max_digits=15)),
                ('lower_quartile', models.DecimalField(decimal_places=2, help_text='LQ - Lower Quartile', max_digits=15)),
                ('median', models.DecimalField(decimal_places=2, help_text='M - Median', max_digits=15)),
                ('upper_quartile', models.DecimalField(decimal_places=2, help_text='UQ - Upper Quartile', max_digits=15)),
                ('upper_decile', models.DecimalField(decimal_places=2, help_text='UD - Upper Decile', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_grades', to='grading.gradingsystem')),
                ('position_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_grades', to='api.positiongroup')),
            ],
            options={
                'ordering': ['position_group__hierarchy_level'],
                'unique_together': {('grading_system', 'position_group')},
            },
        ),
        migrations.AddIndex(
            model_name='salaryscenario',
            index=models.Index(fields=['grading_system', 'status'], name='grading_sal_grading_69c637_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryscenario',
            index=models.Index(fields=['status', 'created_at'], name='grading_sal_status_a7d1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryscenario',
            index=django.contrib.postgres.indexes.GinIndex(fields=['calculated_grades'], name='grading_sal_calcula_80b09d_gin'),
        ),
        migrations.AddIndex(
            model_name='salaryscenario',
            index=django.contrib.postgres.indexes.GinIndex(fields=['input_rates'], name='grading_sal_input_r_157462_gin'),
        ),
    ]
