# Generated by Django 5.2.1 on 2025-06-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status avtomatik olaraq contract və tarix əsasında təyin edilir', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.employeestatus'),
        ),
    ]
