# Generated by Django 5.2.1 on 2025-06-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadcountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(unique=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('active_employees', models.IntegerField(default=0)),
                ('inactive_employees', models.IntegerField(default=0)),
                ('vacant_positions', models.IntegerField(default=0)),
                ('headcount_by_function', models.JSONField(default=dict)),
                ('headcount_by_department', models.JSONField(default=dict)),
                ('headcount_by_position', models.JSONField(default=dict)),
                ('headcount_by_status', models.JSONField(default=dict)),
                ('contract_analysis', models.JSONField(default=dict)),
                ('avg_years_of_service', models.FloatField(default=0)),
                ('new_hires_month', models.IntegerField(default=0)),
                ('departures_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Headcount Summary',
                'verbose_name_plural': 'Headcount Summaries',
                'ordering': ['-summary_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='businessfunction',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['business_function__code']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='employeeactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Activity', 'verbose_name_plural': 'Employee Activities'},
        ),
        migrations.AlterModelOptions(
            name='employeetag',
            options={'ordering': ['tag_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['department__business_function__code']},
        ),
        migrations.RenameField(
            model_name='employeeactivity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('business_function', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('department', 'name')},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='businessfunction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='api.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='grading_level',
            field=models.CharField(blank=True, help_text='Specific grading level (e.g., MGR_UQ)', max_length=10),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='affects_headcount',
            field=models.BooleanField(default=True, help_text='Whether this status counts toward active headcount'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='allows_org_chart',
            field=models.BooleanField(default=True, help_text='Whether employees with this status appear in org chart'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice Period'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned'), ('SUSPENDED', 'Suspended'), ('LEAVE', 'On Leave'), ('VACANT', 'Vacant Position')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='grading_shorthand',
            field=models.CharField(default='', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_headed', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_duration',
            field=models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('3_YEARS', '3 Years'), ('PERMANENT', 'Permanent')], default='PERMANENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, help_text='Current salary grade from grading system', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.employeestatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
      
        migrations.AlterField(
            model_name='employeetag',
            name='tag_type',
            field=models.CharField(choices=[('LEAVE', 'Leave Related'), ('STATUS', 'Status Related'), ('SKILL', 'Skill Related'), ('PROJECT', 'Project Related'), ('PERFORMANCE', 'Performance Related'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobfunction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='VacantPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(help_text='Unique vacancy identifier', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vacancy_type', models.CharField(choices=[('NEW_POSITION', 'New Position'), ('REPLACEMENT', 'Replacement'), ('EXPANSION', 'Expansion'), ('TEMPORARY', 'Temporary')], max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('expected_start_date', models.DateField()),
                ('expected_salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.businessfunction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_filled', to='api.employee')),
                ('job_function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.jobfunction')),
                ('position_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.positiongroup')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacant_positions_managed', to='api.employee')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.unit')),
            ],
            options={
                'verbose_name': 'Vacant Position',
                'verbose_name_plural': 'Vacant Positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='filled_vacancy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_employee', to='api.vacantposition'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='api_employe_employe_0a2b07_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['start_date'], name='api_employe_start_d_c2c773_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='api_employe_status__0de287_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position_group'], name='api_employe_positio_04a61e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business_function', 'department'], name='api_employe_busines_e98ec8_idx'),
        ),
    ]
