# Generated by Django 5.2.1 on 2025-07-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employee_grade_businessfunction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Employee Status', 'verbose_name_plural': 'Employee Statuses'},
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order for status'),
        ),
    ]
