# Generated by Django 5.2.1 on 2025-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employeestatus_options_employeestatus_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='auto_transition_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic status transitions'),
        ),
    ]
