# Generated by Django 5.2.1 on 2025-07-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employeestatus_auto_transition_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='auto_transition_days',
            field=models.IntegerField(blank=True, help_text='Days after which to auto-transition', null=True),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='auto_transition_to',
            field=models.ForeignKey(blank=True, help_text='Status to transition to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='api.employeestatus'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='is_system_status',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this is a system-managed status', null=True),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='is_transitional',
            field=models.BooleanField(default=False, help_text='Whether this is a transitional status'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='notification_template',
            field=models.TextField(blank=True, default='', help_text='Notification template'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='send_notifications',
            field=models.BooleanField(default=False, help_text='Send notifications for this status'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='transition_priority',
            field=models.IntegerField(blank=True, default=0, help_text='Priority for transitions', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='onboarding_duration',
            field=models.IntegerField(blank=True, default=7, help_text='Onboarding duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for status'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_1y',
            field=models.IntegerField(blank=True, default=90, help_text='Probation duration for 1-year contracts', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_2y',
            field=models.IntegerField(blank=True, default=90, help_text='Probation duration for 2-year contracts', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_3m',
            field=models.IntegerField(blank=True, default=7, help_text='Probation duration for 3-month contracts', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_3y',
            field=models.IntegerField(blank=True, default=90, help_text='Probation duration for 3-year contracts', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_6m',
            field=models.IntegerField(blank=True, default=14, help_text='Probation duration for 6-month contracts', null=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='probation_duration_permanent',
            field=models.IntegerField(blank=True, default=0, help_text='Probation duration for permanent contracts', null=True),
        ),
    ]
