# Generated by Django 5.2.1 on 2025-07-08 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contracttypeconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='is_default_for_new_employees',
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='is_system_status',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this is a system-managed status', null=True),
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_type', models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('3_YEARS', '3 Years'), ('PERMANENT', 'Permanent')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('onboarding_duration', models.IntegerField(default=7, help_text='Onboarding duration in days')),
                ('probation_duration', models.IntegerField(default=90, help_text='Probation duration in days')),
                ('auto_transition_enabled', models.BooleanField(default=True, help_text='Enable automatic status transitions')),
                ('is_renewable', models.BooleanField(default=True, help_text='Whether this contract type can be renewed')),
                ('max_renewals', models.IntegerField(default=3, help_text='Maximum number of renewals allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_active_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_contracts', to='api.employeestatus')),
                ('default_inactive_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactive_contracts', to='api.employeestatus')),
                ('default_onboarding_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_contracts', to='api.employeestatus')),
                ('default_probation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_contracts', to='api.employeestatus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
                'ordering': ['duration_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.contracttype'),
        ),
        migrations.DeleteModel(
            name='ContractTypeConfig',
        ),
    ]
