# Generated by Django 5.2.1 on 2025-07-08 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_employee_contract_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Contract type name (e.g., 3 Months, 6 Months, etc.)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Contract code (e.g., 3M, 6M, 1Y, PERM)', max_length=20, unique=True)),
                ('duration_months', models.IntegerField(blank=True, help_text='Duration in months (null for permanent)', null=True)),
                ('is_permanent', models.BooleanField(default=False, help_text='Is this a permanent contract type')),
                ('is_active', models.BooleanField(default=True)),
                ('onboarding_days', models.IntegerField(default=7, help_text='Days for onboarding status')),
                ('probation_days', models.IntegerField(default=0, help_text='Days for probation status')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='contracttypeconfig',
            name='deleted_by',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='api_employe_line_ma_ae4a28_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_duration',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='is_default_for_new_employees',
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='is_system_status',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this is a system-managed status', null=True),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(default='', help_text='Type of contract', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.contracttype'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['contract_type'], name='api_employe_contrac_94d62e_idx'),
        ),
        migrations.DeleteModel(
            name='ContractTypeConfig',
        ),
    ]
