# Generated by Django 5.2.1 on 2025-07-08 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contracttype_remove_contracttypeconfig_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('3_YEARS', '3 Years'), ('PERMANENT', 'Permanent')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('onboarding_days', models.IntegerField(default=7, help_text='Days for onboarding status')),
                ('probation_days', models.IntegerField(default=0, help_text='Days for probation status after onboarding')),
                ('enable_auto_transitions', models.BooleanField(default=True, help_text='Enable automatic status transitions')),
                ('transition_to_inactive_on_end', models.BooleanField(default=True, help_text='Auto transition to inactive when contract ends')),
                ('notify_days_before_end', models.IntegerField(default=30, help_text='Days before contract end to send notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Type Configuration',
                'verbose_name_plural': 'Contract Type Configurations',
                'ordering': ['contract_type'],
            },
        ),
        migrations.RemoveField(
            model_name='contracttype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_type',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='api_employe_contrac_94d62e_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_duration',
            field=models.CharField(choices=[('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEARS', '2 Years'), ('3_YEARS', '3 Years'), ('PERMANENT', 'Permanent')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this status'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='is_default_for_new_employees',
            field=models.BooleanField(default=False, help_text='Use as default for new employees'),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored'), ('BULK_CREATED', 'Bulk Created'), ('STATUS_AUTO_UPDATED', 'Status Auto Updated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='is_system_status',
            field=models.BooleanField(default=False, help_text='Whether this is a system-managed status'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['line_manager'], name='api_employe_line_ma_ae4a28_idx'),
        ),
        migrations.AddField(
            model_name='contracttypeconfig',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
    ]
