# Generated by Django 5.2.1 on 2025-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contracttypeconfig_remove_contracttype_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name", max_length=100, null=True),
        ),
    ]
