# Generated by Django 5.2.1 on 2025-07-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='father_name',
        ),
    ]
