# Generated by Django 5.2.1 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_employee_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name (optional)", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('STATUS_AUTO_UPDATED', 'Status Auto Updated'), ('MANAGER_CHANGED', 'Manager Changed'), ('MANAGER_ASSIGNED', 'Manager Assigned'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored'), ('BULK_CREATED', 'Bulk Created'), ('LINE_MANAGER_BULK_UPDATE', 'Line Manager Bulk Update')], max_length=30),
        ),
    ]
