# Generated by Django 5.2.1 on 2025-07-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_employee_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='father_name',
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored'), ('BULK_CREATED', 'Bulk Created'), ('STATUS_AUTO_UPDATED', 'Status Auto Updated')], max_length=20),
        ),
    ]
