# Generated by Django 5.2.1 on 2025-07-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_employee_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's name (optional)", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Line manager for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='api.employee'),
        ),
    ]
