# Generated by Django 5.2.1 on 2025-07-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_employee_father_name_alter_employee_line_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadcountSummary',
        ),
    ]
