# Generated by Django 5.2.1 on 2025-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_headcountsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttypeconfig',
            name='contract_type',
            field=models.CharField(help_text='Contract type identifier (e.g., 3_MONTHS, 5_MONTHS, 18_MONTHS, etc.)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_duration',
            field=models.CharField(default='PERMANENT', help_text='Contract duration type - references ContractTypeConfig', max_length=50),
        ),
    ]
