# Generated by Django 5.2.1 on 2025-07-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_employeedocument_options_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Employee profile photo', null=True, upload_to='employee_profiles/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='FileUploadSession',
        ),
    ]
