# Generated by Django 5.2.1 on 2025-07-16 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_employeedocument_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Employee Documents'},
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='description',
            field=models.TextField(blank=True, help_text='Document description'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload document file', null=True, upload_to='employee_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Current status of the document', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Document expiry date', null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Mark as confidential'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_current_version',
            field=models.BooleanField(default=True, help_text='Is this the current version?'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Is this document required for employee?'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='notify_before_expiry_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to send notification'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='Document that replaces this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='api.employeedocument'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Document version number'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('ID', 'ID Document'), ('CERTIFICATE', 'Certificate'), ('CV', 'Curriculum Vitae'), ('PERFORMANCE', 'Performance Review'), ('MEDICAL', 'Medical Certificate'), ('TRAINING', 'Training Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='name',
            field=models.CharField(help_text='Document name or title', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True), ('is_deleted', False)), fields=('employee', 'name', 'document_type'), name='unique_current_version_per_employee_document'),
        ),
    ]
