# Generated by Django 5.2.1 on 2025-07-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_employeedocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='renewal_status',
        ),
    ]
