# Generated by Django 5.2.1 on 2025-08-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_employee_renewal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantposition',
            name='display_name',
            field=models.CharField(default='', editable=False, help_text='Display name for employee lists', max_length=300),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='grading_level',
            field=models.CharField(default='', help_text='Expected grading level for this position', max_length=15),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='include_in_headcount',
            field=models.BooleanField(default=True, help_text='Include this vacancy in headcount calculations'),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='is_visible_in_org_chart',
            field=models.BooleanField(default=True, help_text='Show in organizational chart as vacant position'),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='vacancy_status',
            field=models.ForeignKey(default='', limit_choices_to={'status_type': 'VACANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='vacant_positions', to='api.employeestatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='filled_vacancy',
            field=models.OneToOneField(blank=True, help_text='Vacancy that this employee was hired for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_who_filled', to='api.vacantposition'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='filled_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_vacancy_position', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='position_id',
            field=models.CharField(help_text='Unique vacancy identifier (acts as employee ID)', max_length=50, unique=True),
        ),
    ]
