# Generated by Django 5.2.1 on 2025-08-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_vacantposition_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='filled_vacancy',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='filled_by',
        ),
        migrations.AddField(
            model_name='employee',
            name='original_vacancy',
            field=models.OneToOneField(blank=True, help_text='Original vacancy this employee was hired for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hired_for_position', to='api.vacantposition'),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='filled_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_vacancy_position', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='display_name',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='grading_level',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='include_in_headcount',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='is_visible_in_org_chart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='position_id',
            field=models.CharField(help_text='Unique vacancy identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vacant_positions', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='vacancy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacant_positions_with_status', to='api.employeestatus'),
        ),
    ]
