# Generated by Django 5.2.1 on 2025-08-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_behavioralcompetencygroup_behavioralcompetency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecompetencyassessment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeecompetencyassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyassessment',
            name='behavioral_competency',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyassessment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyassessment',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CompetencyMatrix',
        ),
        migrations.DeleteModel(
            name='EmployeeCompetencyAssessment',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
