# Generated by Django 5.2.1 on 2025-08-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_employeecompetencyassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavioralcompetency',
            name='description',
        ),
        migrations.RemoveField(
            model_name='behavioralcompetencygroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skillgroup',
            name='description',
        ),
    ]
