# Generated by Django 5.2.1 on 2025-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_accessmatrix_companybenefit_jobbusinessresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestatus',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice Period'), ('LEAVE', 'On Leave'), ('VACANT', 'Vacant Position')], default='ACTIVE', max_length=20),
        ),
    ]
