# Generated by Django 5.2.1 on 2025-08-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_employeestatus_status_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfunction',
            name='description',
        ),
    ]
