# Generated by Django 5.2.1 on 2025-08-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_jobfunction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessfunction',
            name='description',
        ),
    ]
