# Generated by Django 5.2.1 on 2025-08-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_businessfunction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='employeetag',
            name='tag_type',
        ),
    ]
