# Generated by Django 5.2.1 on 2025-08-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_employeetag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='job_function',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.jobfunction', verbose_name='Job Function'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('NOTICE_PERIOD', 'Notice Period'), ('VACANT', 'Vacant Position')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='manual_employee_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Employee Name (for vacant positions)'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='manual_employee_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employee Phone (for vacant positions)'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text="Automatically assigned based on selected employee's line manager", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_job_descriptions', to='api.employee', verbose_name="Reports To (Auto-assigned from Employee's Manager)"),
        ),
    ]
