# Generated by Django 5.2.1 on 2025-08-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_jobdescription_job_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessmatrix',
            options={'ordering': ['name', 'description'], 'verbose_name_plural': 'Access Matrix'},
        ),
        migrations.AlterModelOptions(
            name='companybenefit',
            options={'ordering': ['description', 'name']},
        ),
        migrations.AlterModelOptions(
            name='jobbusinessresource',
            options={'ordering': ['description', 'name']},
        ),
        migrations.RemoveField(
            model_name='accessmatrix',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='companybenefit',
            name='benefit_type',
        ),
        migrations.RemoveField(
            model_name='jobbusinessresource',
            name='category',
        ),
    ]
