# Generated by Django 5.2.1 on 2025-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_asset_assetactivity_assetcategory_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='archive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
