# Generated by Django 5.2.1 on 2025-08-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_asset_archive_reason_alter_asset_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='specifications',
        ),
    ]
