# Generated by Django 5.2.1 on 2025-08-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_employeeactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Activity', 'verbose_name_plural': 'Employee Activities'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned (Pending Approval)'), ('IN_USE', 'In Use'), ('NEED_CLARIFICATION', 'Need Clarification'), ('IN_REPAIR', 'In Repair'), ('ARCHIVED', 'Archived')], default='IN_STOCK', max_length=15),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored'), ('BULK_CREATED', 'Bulk Created'), ('STATUS_AUTO_UPDATED', 'Status Auto Updated')], max_length=20),
        ),
    ]
