# Generated by Django 5.2.1 on 2025-08-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_employeeactivity_options_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned (Pending Approval)'), ('IN_USE', 'In Use'), ('NEED_CLARIFICATION', 'Need Clarification'), ('IN_REPAIR', 'In Repair'), ('ARCHIVED', 'Archived')], default='IN_STOCK', max_length=25),
        ),
    ]
