# Generated by Django 5.2.1 on 2025-08-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned to Employee'), ('ACCEPTED', 'Accepted by Employee'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CHECKED_IN', 'Checked In'), ('STATUS_CHANGED', 'Status Changed'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored from Archive')], max_length=30),
        ),
    ]
