# Generated by Django 5.2.1 on 2025-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_assetactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='condition_on_checkin',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=35),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='condition_on_checkout',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=30),
        ),
    ]
