# Generated by Django 5.2.1 on 2025-08-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_assetassignment_condition_on_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('MANAGER_CHANGED', 'Manager Changed'), ('POSITION_CHANGED', 'Position Changed'), ('CONTRACT_UPDATED', 'Contract Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('GRADE_CHANGED', 'Grade Changed'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('SOFT_DELETED', 'Employee Soft Deleted'), ('RESTORED', 'Employee Restored'), ('BULK_CREATED', 'Bulk Created'), ('STATUS_AUTO_UPDATED', 'Status Auto Updated'), ('ASSET_ACCEPTED', 'Asset Accepted'), ('ASSET_CLARIFICATION_REQUESTED', 'Asset Clarification Requested')], max_length=30),
        ),
    ]
