# Generated by Django 5.2.1 on 2025-08-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_employee_clarification_provided_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='clarification_provided_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clarification_provided_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clarification_requested_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clarification_requested_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clarification_requested_reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clarification_response',
        ),
    ]
