# Generated by Django 5.2.1 on 2025-09-01 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_lettergrademapping_behavioralscale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behavioralscale',
            options={'ordering': ['scale']},
        ),
        migrations.AlterModelOptions(
            name='corecompetencyscale',
            options={'ordering': ['scale']},
        ),
        migrations.RemoveField(
            model_name='behavioralscale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='behavioralscale',
            name='scale_definitions',
        ),
        migrations.RemoveField(
            model_name='corecompetencyscale',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='corecompetencyscale',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='corecompetencyscale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='corecompetencyscale',
            name='scale_levels',
        ),
        migrations.RemoveField(
            model_name='positionbehavioralassessment',
            name='behavioral_scale',
        ),
        migrations.RemoveField(
            model_name='positioncoreassessment',
            name='scale',
        ),
        migrations.AddField(
            model_name='behavioralscale',
            name='scale',
            field=models.IntegerField(default=1, help_text='Scale number/level', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corecompetencyscale',
            name='scale',
            field=models.IntegerField(default=1, help_text='Scale number/level', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='behavioralscale',
            name='description',
            field=models.TextField(help_text='Description of this scale'),
        ),
        migrations.AlterField(
            model_name='employeebehavioralcompetencyrating',
            name='actual_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employeebehavioralcompetencyrating',
            name='required_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employeecorecompetencyrating',
            name='actual_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employeecorecompetencyrating',
            name='required_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='positionbehavioralcompetencyrating',
            name='required_level',
            field=models.IntegerField(help_text='Required behavioral competency level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='positioncorecompetencyrating',
            name='required_level',
            field=models.IntegerField(help_text='Required proficiency level for this position', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
