# Generated by Django 5.2.1 on 2025-09-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_behavioralscale_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettergrademapping',
            name='color',
        ),
    ]
