# Generated by Django 5.2.1 on 2025-09-01 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_lettergrademapping_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebehavioralassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When assessment was completed', null=True),
        ),
        migrations.AddField(
            model_name='employeebehavioralassessment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_behavioral_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecoreassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When assessment was completed', null=True),
        ),
        migrations.AddField(
            model_name='employeecoreassessment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_core_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeebehavioralassessment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='employeebehavioralassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - In Progress'), ('COMPLETED', 'Completed - Final')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeecoreassessment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='employeecoreassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - In Progress'), ('COMPLETED', 'Completed - Final')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeebehavioralassessment',
            index=models.Index(fields=['employee', 'status'], name='employee_be_employe_9bf42e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebehavioralassessment',
            index=models.Index(fields=['assessment_date'], name='employee_be_assessm_78f06c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebehavioralassessment',
            index=models.Index(fields=['status', 'completed_at'], name='employee_be_status_df4058_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecoreassessment',
            index=models.Index(fields=['employee', 'status'], name='employee_co_employe_cb0c86_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecoreassessment',
            index=models.Index(fields=['assessment_date'], name='employee_co_assessm_827087_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecoreassessment',
            index=models.Index(fields=['status', 'completed_at'], name='employee_co_status_785873_idx'),
        ),
    ]
