# Generated by Django 5.2.1 on 2025-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_employeebehavioralassessment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeebehavioralassessment',
            name='employee_be_employe_9bf42e_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeebehavioralassessment',
            name='employee_be_assessm_78f06c_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeebehavioralassessment',
            name='employee_be_status_df4058_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeecoreassessment',
            name='employee_co_employe_cb0c86_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeecoreassessment',
            name='employee_co_assessm_827087_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeecoreassessment',
            name='employee_co_status_785873_idx',
        ),
        migrations.RemoveField(
            model_name='employeebehavioralassessment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='employeebehavioralassessment',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='employeecoreassessment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='employeecoreassessment',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='employeebehavioralassessment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeebehavioralassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeecoreassessment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeecoreassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
    ]
