# Generated by Django 5.2.1 on 2025-09-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_employeebehavioralassessment_employee_be_employe_9bf42e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebehavioralassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='employeecoreassessment',
            name='assessed_by',
        ),
    ]
