# Generated by Django 5.2.1 on 2025-09-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_employeebehavioralassessment_assessed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebehavioralassessment',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='employeecoreassessment',
            name='assessment_date',
        ),
    ]
