# Generated by Django 5.2.1 on 2025-09-03 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_employeebehavioralassessment_assessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebehavioralassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeecoreassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
