# Generated by Django 5.2.1 on 2025-09-03 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_employeebehavioralassessment_assessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebehavioralassessment',
            name='assessment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeecoreassessment',
            name='assessment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
