# Generated by Django 5.2.1 on 2025-09-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_jobdescription_manual_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='matched_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_job_descriptions', to='api.employee', verbose_name='Matched Employee (Auto-selected)'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='business_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessfunction'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobfunction'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='position_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.positiongroup'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_job_descriptions', to='api.employee', verbose_name='Reports To (Auto-assigned)'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit'),
        ),
    ]
