# Generated by Django 5.2.1 on 2025-09-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_jobdescription_assigned_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='matched_employee',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_descriptions', to='api.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='manual_employee_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Employee Name (for vacant positions)'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='manual_employee_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employee Phone (for vacant positions)'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='business_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessfunction', verbose_name='Business Function'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(help_text='Grading level from position group', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobfunction', verbose_name='Job Function'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='position_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.positiongroup', verbose_name='Position Group/Hierarchy'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text="Automatically assigned based on selected employee's line manager", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_job_descriptions', to='api.employee', verbose_name="Reports To (Auto-assigned from Employee's Manager)"),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit', verbose_name='Unit'),
        ),
    ]
