# Generated by Django 5.2.1 on 2025-09-10 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_jobdescription_matched_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessmatrix',
            options={'ordering': ['name'], 'verbose_name_plural': 'Access Matrix'},
        ),
        migrations.AlterModelOptions(
            name='companybenefit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jobbusinessresource',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='manual_employee_name',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='manual_employee_phone',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(editable=False, help_text='Auto-generated based on Business Function code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='assigned_employee',
            field=models.ForeignKey(default=1, help_text='Employee for this job description - filtered based on organizational structure', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_descriptions', to='api.employee', verbose_name='Assigned Employee'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['assigned_employee'], name='job_descrip_assigne_ed57e8_idx'),
        ),
    ]
