# Generated by Django 5.2.1 on 2025-09-10 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_accessmatrix_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantposition',
            name='title',
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='job_title',
            field=models.CharField(default='', help_text='Job title for the vacant position', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this position'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='business_function',
            field=models.ForeignKey(help_text='Business function (required)', on_delete=django.db.models.deletion.PROTECT, to='api.businessfunction'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='department',
            field=models.ForeignKey(help_text='Department (required)', on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed job description'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='grading_level',
            field=models.CharField(help_text='Grading level (e.g., MGR_UQ)', max_length=15),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='include_in_headcount',
            field=models.BooleanField(default=True, help_text='Include this position in headcount calculations'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='is_visible_in_org_chart',
            field=models.BooleanField(default=True, help_text='Show this position in organizational chart'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='job_function',
            field=models.ForeignKey(help_text='Job function (required)', on_delete=django.db.models.deletion.PROTECT, to='api.jobfunction'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='position_group',
            field=models.ForeignKey(help_text='Position group (required)', on_delete=django.db.models.deletion.PROTECT, to='api.positiongroup'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='position_id',
            field=models.CharField(editable=False, help_text='Auto-generated vacancy ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='Line manager for this position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vacant_positions', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.unit'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='vacancy_type',
            field=models.CharField(choices=[('NEW_POSITION', 'New Position'), ('REPLACEMENT', 'Replacement'), ('EXPANSION', 'Expansion'), ('TEMPORARY', 'Temporary')], default='NEW_POSITION', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_employee_id', models.CharField(db_index=True, max_length=50)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=200)),
                ('business_function_name', models.CharField(blank=True, max_length=100)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('unit_name', models.CharField(blank=True, max_length=100)),
                ('job_function_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_duration', models.CharField(max_length=50)),
                ('line_manager_name', models.CharField(blank=True, max_length=300)),
                ('deletion_reason', models.CharField(choices=[('SOFT_DELETE', 'Soft Delete'), ('HARD_DELETE', 'Hard Delete'), ('CONTRACT_END', 'Contract Ended'), ('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination')], max_length=50)),
                ('deleted_at', models.DateTimeField()),
                ('original_data', models.JSONField(default=dict, help_text='Complete original employee data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Archive',
                'verbose_name_plural': 'Employee Archives',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['original_employee_id'], name='api_employe_origina_1c4453_idx'), models.Index(fields=['deleted_at'], name='api_employe_deleted_b32bcf_idx'), models.Index(fields=['deletion_reason'], name='api_employe_deletio_98d7ac_idx')],
            },
        ),
    ]
