# Generated by Django 5.2.1 on 2025-09-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_vacantposition_title_vacantposition_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='expected_salary_range_max',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='expected_salary_range_min',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='expected_start_date',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='vacancy_type',
        ),
    ]
