# Generated by Django 5.2.1 on 2025-09-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_vacantposition_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeearchive',
            name='archive_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='employeearchive',
            name='data_quality',
            field=models.CharField(choices=[('COMPLETE', 'Complete Data'), ('PARTIAL', 'Partial Data'), ('BASIC', 'Basic Info Only'), ('MINIMAL', 'Minimal Data')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='employeearchive',
            name='deletion_notes',
            field=models.TextField(blank=True, help_text='Additional notes about deletion'),
        ),
        migrations.AlterField(
            model_name='employeearchive',
            name='deletion_reason',
            field=models.CharField(choices=[('SOFT_DELETE', 'Soft Delete'), ('HARD_DELETE', 'Hard Delete'), ('CONTRACT_END', 'Contract Ended'), ('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('BULK_RESTRUCTURING', 'Bulk Restructuring'), ('DATA_CLEANUP', 'Data Cleanup'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeearchive',
            name='original_data',
            field=models.JSONField(default=dict, help_text='Complete original employee data in JSON format'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='business_function',
            field=models.ForeignKey(help_text='Business function (required for position_id generation)', on_delete=django.db.models.deletion.PROTECT, to='api.businessfunction'),
        ),
        migrations.AlterField(
            model_name='vacantposition',
            name='position_id',
            field=models.CharField(editable=False, help_text='Auto-generated position ID based on business function code', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='employeearchive',
            index=models.Index(fields=['data_quality'], name='api_employe_data_qu_25d511_idx'),
        ),
        migrations.AddIndex(
            model_name='employeearchive',
            index=models.Index(fields=['business_function_name'], name='api_employe_busines_99b718_idx'),
        ),
        migrations.AddIndex(
            model_name='employeearchive',
            index=models.Index(fields=['department_name'], name='api_employe_departm_930904_idx'),
        ),
    ]
