# Generated by Django 5.2.1 on 2025-09-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_employeearchive_archive_version_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeearchive',
            name='api_employe_deletio_98d7ac_idx',
        ),
        migrations.RemoveField(
            model_name='employeearchive',
            name='deletion_reason',
        ),
    ]
