# Generated by Django 5.2.1 on 2025-09-11 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_employeearchive_api_employe_deletio_98d7ac_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeearchive',
            name='employee_still_exists',
            field=models.BooleanField(default=False, help_text='True if this was a soft delete and employee data still exists in main table'),
        ),
        migrations.AddField(
            model_name='employeearchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeearchive',
            name='archive_version',
            field=models.CharField(default='2.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeearchive',
            name='deletion_notes',
            field=models.TextField(blank=True, help_text='Additional notes about deletion and any restorations'),
        ),
        migrations.AddIndex(
            model_name='employeearchive',
            index=models.Index(fields=['employee_still_exists'], name='api_employe_employe_ea2de1_idx'),
        ),
    ]
