# Generated by Django 5.2.1 on 2025-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_employeearchive_employee_still_exists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeearchive',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
