# Generated by Django 5.2.1 on 2025-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_employeearchive_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantposition',
            name='created_from_employee_id',
            field=models.CharField(blank=True, help_text='Original employee ID that this vacancy was created from', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='created_from_employee_name',
            field=models.CharField(blank=True, help_text='Original employee name', max_length=300, null=True),
        ),
    ]
