# Generated by Django 5.2.1 on 2025-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_vacantposition_created_from_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantposition',
            name='created_from_employee_id',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='created_from_employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_from_employee_id',
            field=models.CharField(blank=True, help_text='Original employee ID that this vacancy was created from', max_length=50, null=True),
        ),
    ]
