# Generated by Django 5.2.1 on 2025-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_vacantposition_created_from_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_from_employee_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='original_employee_pk',
            field=models.IntegerField(blank=True, help_text='Original employee database ID (pk) that created this vacancy', null=True),
        ),
        migrations.AddField(
            model_name='vacantposition',
            name='original_employee_pk',
            field=models.IntegerField(blank=True, help_text='Original employee database ID (pk) that created this vacancy', null=True),
        ),
    ]
