# Generated by Django 5.2.1 on 2025-09-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_employee_created_from_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='job_descrip_job_tit_1d02ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='job_descrip_status_7b0350_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='job_descrip_busines_0e1b7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='job_descrip_created_a5d3de_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='job_descrip_assigne_ed57e8_idx',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='assigned_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_descriptions', to='api.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_job_descriptions', to='api.employee', verbose_name='Reports To'),
        ),
    ]
