# Generated by Django 5.2.1 on 2025-09-17 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_jobdescription_job_descrip_job_tit_1d02ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_purpose',
            field=models.TextField(help_text='Main purpose and objectives of the role', validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
