# Generated by Django 5.2.1 on 2025-09-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_jobdescription_job_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_descriptions', to='api.employee', verbose_name='Assigned Employee'),
        ),
    ]
