# Generated by Django 5.2.1 on 2025-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_jobdescription_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeearchive',
            name='original_employee_pk',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
