# Generated by Django 5.2.1 on 2025-09-19 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_employeearchive_original_employee_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeearchive',
            index=models.Index(fields=['original_employee_pk'], name='api_employe_origina_e96706_idx'),
        ),
    ]
