# Generated by Django 5.2.1 on 2025-09-22 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_vacationrequest_vacationactivity_vacationsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationactivity',
            name='vacation_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.vacationschedule'),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='start_balance',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Starting balance for the year (remaining from previous year)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacationactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Request Created'), ('SUBMITTED', 'Request Submitted'), ('APPROVED_LINE_MANAGER', 'Approved by Line Manager'), ('REJECTED_LINE_MANAGER', 'Rejected by Line Manager'), ('APPROVED_HR', 'Approved by HR'), ('REJECTED_HR', 'Rejected by HR'), ('EDITED', 'Request Edited'), ('CANCELLED', 'Request Cancelled'), ('REGISTERED', 'Vacation Registered'), ('SCHEDULE_CREATED', 'Schedule Created'), ('SCHEDULE_EDITED', 'Schedule Edited')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vacationactivity',
            name='vacation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.vacationrequest'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PENDING_LINE_MANAGER', 'Pending Line Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED_LINE_MANAGER', 'Rejected by Line Manager'), ('REJECTED_HR', 'Rejected by HR'), ('CANCELLED', 'Cancelled'), ('REGISTERED', 'Registered'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30),
        ),
    ]
