# Generated by Django 5.2.1 on 2025-09-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_vacationactivity_vacation_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('Vacation Request', 'Vacation Request')], max_length=50)),
                ('stage', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacationactivity',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='vacationactivity',
            name='vacation_request',
        ),
        migrations.RemoveField(
            model_name='vacationactivity',
            name='vacation_schedule',
        ),
        migrations.AlterModelOptions(
            name='employeevacationbalance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacationschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacationsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacationtype',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='vacationrequest',
            name='api_vacatio_employe_87b73f_idx',
        ),
        migrations.RemoveIndex(
            model_name='vacationrequest',
            name='api_vacatio_start_d_b425ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='vacationrequest',
            name='api_vacatio_status_74e8d9_idx',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='edit_count',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='last_edited_at',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='vacationschedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vacationtype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='scheduled_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='start_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='yearly_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='hr_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_hr', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_to_approve', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='line_manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='request_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SCHEDULING', 'Scheduling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vacation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PENDING_LINE_MANAGER', 'Pending Line Manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED_LINE_MANAGER', 'Rejected by Line Manager'), ('REJECTED_HR', 'Rejected by HR')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='allow_negative_balance',
            field=models.BooleanField(default=False, help_text='Balans 0 olduqda request yaratmağa icazə'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='default_hr_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_settings', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='max_schedule_edits',
            field=models.PositiveIntegerField(default=3, help_text='Schedule neçə dəfə edit oluna bilər'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='non_working_days',
            field=models.JSONField(default=list, help_text="['2025-01-01', '2025-03-08', ...]"),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='notification_days_before',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='notification_frequency',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VacationActivity',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('request_type', 'stage')},
        ),
    ]
