# Generated by Django 5.2.1 on 2025-09-24 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_notificationtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeevacationbalance',
            options={'ordering': ['-year', 'employee__full_name'], 'verbose_name': 'Employee Vacation Balance', 'verbose_name_plural': 'Employee Vacation Balances'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['request_type', 'stage'], 'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Templates'},
        ),
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vacation Request', 'verbose_name_plural': 'Vacation Requests'},
        ),
        migrations.AlterModelOptions(
            name='vacationschedule',
            options={'ordering': ['-start_date'], 'verbose_name': 'Vacation Schedule', 'verbose_name_plural': 'Vacation Schedules'},
        ),
        migrations.AlterModelOptions(
            name='vacationsetting',
            options={'verbose_name': 'Vacation Setting', 'verbose_name_plural': 'Vacation Settings'},
        ),
        migrations.AlterModelOptions(
            name='vacationtype',
            options={'ordering': ['name'], 'verbose_name': 'Vacation Type', 'verbose_name_plural': 'Vacation Types'},
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='scheduled_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Planlaşdırılmış günlər', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='start_balance',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Əvvəlki ildən qalan balans', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='İstifadə edilmiş günlər', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='year',
            field=models.PositiveIntegerField(help_text='İl (məsələn: 2025)'),
        ),
        migrations.AlterField(
            model_name='employeevacationbalance',
            name='yearly_balance',
            field=models.DecimalField(decimal_places=1, default=0, help_text='İllik məzuniyyət balansı', max_digits=5),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text='Email məzmunu (variables: {employee_name}, {start_date}, etc.)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='request_type',
            field=models.CharField(choices=[('Vacation Request', 'Vacation Request'), ('Business Trip', 'Business Trip'), ('Remote Work', 'Remote Work')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='stage',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Upcoming Reminder', 'Upcoming Reminder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(help_text='Email mövzusu', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='comment',
            field=models.TextField(blank=True, help_text='İşçinin şərhi'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='request_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SCHEDULING', 'Scheduling')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='allow_negative_balance',
            field=models.BooleanField(default=False, help_text='Balans 0 olduqda request yaratmağa icazə ver'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='default_hr_representative',
            field=models.ForeignKey(blank=True, help_text='Default HR nümayəndəsi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_settings', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='non_working_days',
            field=models.JSONField(default=list, help_text="Qeyri-iş günləri JSON formatında: ['2025-01-01', '2025-03-08', ...]"),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='notification_days_before',
            field=models.PositiveIntegerField(default=7, help_text='Məzuniyyət başlamazdan neçə gün əvvəl bildiriş göndər'),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='notification_frequency',
            field=models.PositiveIntegerField(default=2, help_text='Bildirişi neçə dəfə göndər'),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='affects_balance',
            field=models.BooleanField(default=True, help_text='Balansa təsir edirmi'),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='code',
            field=models.CharField(help_text='Qısa kod', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color kod (məsələn: #FF5733)', max_length=7),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Təsvir'),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='max_consecutive_days',
            field=models.PositiveIntegerField(blank=True, help_text='Ardıcıl maksimum günlər', null=True),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='name',
            field=models.CharField(help_text='Məzuniyyət növü adı', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Təsdiq tələb edirmi'),
        ),
        migrations.AlterModelTable(
            name='employeevacationbalance',
            table='employee_vacation_balances',
        ),
        migrations.AlterModelTable(
            name='notificationtemplate',
            table='notification_templates',
        ),
        migrations.AlterModelTable(
            name='vacationrequest',
            table='vacation_requests',
        ),
        migrations.AlterModelTable(
            name='vacationschedule',
            table='vacation_schedules',
        ),
        migrations.AlterModelTable(
            name='vacationsetting',
            table='vacation_settings',
        ),
        migrations.AlterModelTable(
            name='vacationtype',
            table='vacation_types',
        ),
    ]
