# Generated by Django 5.2.1 on 2025-09-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationtype',
            name='affects_balance',
        ),
        migrations.RemoveField(
            model_name='vacationtype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='vacationtype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vacationtype',
            name='max_consecutive_days',
        ),
        migrations.RemoveField(
            model_name='vacationtype',
            name='requires_approval',
        ),
    ]
