# Generated by Django 5.2.1 on 2025-09-25 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_vacationtype_affects_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_type_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='number_of_days',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='return_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='number_of_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='return_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vacationsetting',
            name='non_working_days',
            field=models.JSONField(default=list, help_text="Qeyri-iş günləri JSON formatında: [{'date': '2025-01-01', 'name': 'New Year'}, ...]"),
        ),
    ]
