# Generated by Django 5.2.1 on 2025-09-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_notificationtemplate_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
