# Generated by Django 5.2.1 on 2025-09-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
