# Generated by Django 5.2.1 on 2025-09-26 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_approvalworkflow_approvalstep_transporttype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporttype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='traveltype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='trippurpose',
            name='code',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', help_text="Employee's first name", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', help_text="Employee's last name", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account (only created when employee needs system access)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='api_employe_email_5d0ffb_idx'),
        ),
    ]
