# Generated by Django 5.2.1 on 2025-10-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_permission_alter_employee_user_role_employeerole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='expires_at',
        ),
    ]
