# Generated by Django 5.2.1 on 2025-10-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_remove_employeerole_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripNotification',
        ),
    ]
