# Generated by Django 5.2.1 on 2025-10-07 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_delete_tripnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='approvalworkflow',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='workflow',
        ),
        migrations.RenameField(
            model_name='businesstriprequest',
            old_name='approved_amount',
            new_name='finance_amount',
        ),
        migrations.RenameField(
            model_name='businesstriprequest',
            old_name='completed_at',
            new_name='finance_approved_at',
        ),
        migrations.RenameField(
            model_name='businesstriprequest',
            old_name='notes',
            new_name='finance_comment',
        ),
        migrations.RenameField(
            model_name='businesstriprequest',
            old_name='submitted_at',
            new_name='hr_approved_at',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='estimated_amount',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='hr_approver',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='businesstriprequest',
            name='send_sms_reminders',
        ),
        migrations.RemoveField(
            model_name='triphotel',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='comment',
            field=models.TextField(blank=True, help_text='Employee comment'),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_finance_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_hr_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='hr_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='hr_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_hr', to='api.employee'),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='line_manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='line_manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_lm_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='line_manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='number_of_days',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trip_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='return_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_type_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveltype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_type_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippurpose',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippurpose',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_purpose_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='finance_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_finance', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_to_approve', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='requester_type',
            field=models.CharField(choices=[('for_me', 'For Me'), ('for_my_employee', 'For My Employee')], default='for_me', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_LINE_MANAGER', 'Pending Line Manager'), ('PENDING_FINANCE', 'Pending Finance/Payroll'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED_LINE_MANAGER', 'Rejected by Line Manager'), ('REJECTED_FINANCE', 'Rejected by Finance'), ('REJECTED_HR', 'Rejected by HR'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.AlterModelTable(
            name='businesstriprequest',
            table='business_trip_requests',
        ),
        migrations.AlterModelTable(
            name='transporttype',
            table='transport_types',
        ),
        migrations.AlterModelTable(
            name='traveltype',
            table='travel_types',
        ),
        migrations.AlterModelTable(
            name='triphotel',
            table='trip_hotels',
        ),
        migrations.AlterModelTable(
            name='trippurpose',
            table='trip_purposes',
        ),
        migrations.AlterModelTable(
            name='tripschedule',
            table='trip_schedules',
        ),
        migrations.CreateModel(
            name='TripSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_days_before', models.PositiveIntegerField(default=7, help_text='Send notification X days before trip starts')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('default_finance_approver', models.ForeignKey(blank=True, help_text='Default Finance/Payroll approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_finance_settings', to='api.employee')),
                ('default_hr_representative', models.ForeignKey(blank=True, help_text='Default HR representative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_hr_settings', to='api.employee')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Setting',
                'verbose_name_plural': 'Trip Settings',
                'db_table': 'trip_settings',
            },
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
        migrations.DeleteModel(
            name='ApprovalWorkflow',
        ),
    ]
