# Generated by Django 5.2.1 on 2025-10-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_emailtemplate_notificationsettings_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGraphToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Graph Token',
                'verbose_name_plural': 'User Graph Tokens',
                'db_table': 'user_graph_tokens',
            },
        ),
    ]
