# Generated by Django 5.2.1 on 2025-10-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_usergraphtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='default_sender_email',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='default_sender_name',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='microsoft_client_id',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='microsoft_tenant_id',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
