# Generated by Django 5.2.1 on 2025-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_businesstriprequest_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripattachment',
            name='description',
        ),
    ]
