# Generated by Django 5.2.1 on 2025-10-14 06:13

import api.vacation_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_remove_tripattachment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='vacation_subject_prefix',
            field=models.CharField(default='[VACATION]', help_text='Subject prefix for vacation emails (used for filtering in Outlook)', max_length=50),
        ),
        migrations.CreateModel(
            name='VacationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=api.vacation_models.vacation_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vacation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.vacationrequest')),
            ],
            options={
                'verbose_name': 'Vacation Attachment',
                'verbose_name_plural': 'Vacation Attachments',
                'db_table': 'vacation_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
