# Generated by Django 5.2.1 on 2025-10-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_notificationsettings_vacation_subject_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_head',
        ),
    ]
