# Generated by Django 5.2.1 on 2025-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_department_head_of_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
