# Generated by Django 5.2.1 on 2025-10-17 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionbehavioralassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='positionbehavioralassessment',
            name='grade_level',
            field=models.IntegerField(blank=True, help_text='Grade level for this position', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='positionbehavioralassessment',
            unique_together={('position_group', 'job_title', 'grade_level')},
        ),
    ]
