# Generated by Django 5.2.1 on 2025-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_positionbehavioralassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionbehavioralassessment',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade level for this position', max_length=20, null=True),
        ),
    ]
