# Generated by Django 5.2.1 on 2025-10-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_positionbehavioralassessment_grade_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('READ', 'Read Only'), ('WRITE', 'Write'), ('ADMIN', 'Admin'), ('FULL', 'Full Access')], default='READ', max_length=10)),
                ('system_identifier', models.CharField(blank=True, help_text='System ID or endpoint (e.g., aws:s3:bucket-name)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_matrix', models.ForeignKey(help_text='Parent access category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.accessmatrix')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_matrix_items',
                'ordering': ['access_matrix', 'name'],
                'unique_together': {('access_matrix', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyBenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, help_text="Benefit value (e.g., '21 days', '100%', '£500')", max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details like eligibility, conditions, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(help_text='Parent benefit category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.companybenefit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_benefit_items',
                'ordering': ['benefit', 'name'],
                'unique_together': {('benefit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobBusinessResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Additional specs like RAM, Storage, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(help_text='Parent resource category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.jobbusinessresource')),
            ],
            options={
                'db_table': 'job_business_resource_items',
                'ordering': ['resource', 'name'],
                'unique_together': {('resource', 'name')},
            },
        ),
    ]
