# Generated by Django 5.2.1 on 2025-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_accessmatrixitem_companybenefititem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessmatrixitem',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='accessmatrixitem',
            name='system_identifier',
        ),
        migrations.RemoveField(
            model_name='jobbusinessresourceitem',
            name='specifications',
        ),
        migrations.AddField(
            model_name='jobdescriptionaccessmatrix',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific access rights required', related_name='job_descriptions', to='api.accessmatrixitem'),
        ),
        migrations.AddField(
            model_name='jobdescriptionbusinessresource',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific items required (leave empty for any)', related_name='job_descriptions', to='api.jobbusinessresourceitem'),
        ),
        migrations.AddField(
            model_name='jobdescriptioncompanybenefit',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific benefit details', related_name='job_descriptions', to='api.companybenefititem'),
        ),
    ]
