# Generated by Django 5.2.1 on 2025-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_remove_accessmatrixitem_access_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionbehavioralassessment',
            unique_together={('position_group', 'job_title')},
        ),
        migrations.AddField(
            model_name='positionbehavioralassessment',
            name='grade_levels',
            field=models.JSONField(default=list, help_text='List of grade levels for this position'),
        ),
        migrations.RemoveField(
            model_name='positionbehavioralassessment',
            name='grade_level',
        ),
    ]
