# Generated by Django 5.2.1 on 2025-10-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_companynews_newsattachment_targetgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescriptionbehavioralcompetency',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='jobdescriptionbehavioralcompetency',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='jobdescriptionskill',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='jobdescriptionskill',
            name='proficiency_level',
        ),
    ]
