# Generated by Django 5.2.1 on 2025-10-20 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_remove_jobdescriptionbehavioralcompetency_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Announcement', 'Event')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active categories can be used for news')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'db_table': 'company_news_categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='companynews',
            new_name='company_new_categor_d9d2ca_idx',
            old_name='company_new_categor_f9814f_idx',
        ),
        migrations.AddField(
            model_name='newscategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='category',
            field=models.ForeignKey(help_text='News category', on_delete=django.db.models.deletion.PROTECT, related_name='news_items', to='api.newscategory'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['is_active'], name='company_new_is_acti_18f4fc_idx'),
        ),
    ]
