# Generated by Django 5.2.1 on 2025-10-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_notificationsettings_company_news_sender_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='company_news_sender_email',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='company_news_subject_prefix',
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='business_trip_subject_prefix',
            field=models.CharField(default='[BUSINESS TRIP]', help_text='Subject prefix for business trip emails (used for filtering in Outlook)', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='vacation_subject_prefix',
            field=models.CharField(default='[VACATION]', help_text='Subject prefix for vacation emails (used for filtering in Outlook)', max_length=50),
        ),
    ]
