# Generated by Django 5.2.1 on 2025-10-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_remove_notificationsettings_company_news_sender_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsattachment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsattachment',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='NewsActivity',
        ),
        migrations.DeleteModel(
            name='NewsAttachment',
        ),
    ]
