# Generated by Django 5.2.1 on 2025-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_remove_newsattachment_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='company_news_sender_email',
            field=models.EmailField(default='myalmet@almettrading.com', help_text='Email address for sending company news (must be valid Outlook/Exchange mailbox)', max_length=254),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='company_news_subject_prefix',
            field=models.CharField(default='[COMPANY NEWS]', help_text='Subject prefix for company news emails', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='business_trip_subject_prefix',
            field=models.CharField(default='[BUSINESS TRIP]', help_text='Subject prefix for business trip emails', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='vacation_subject_prefix',
            field=models.CharField(default='[VACATION]', help_text='Subject prefix for vacation emails', max_length=50),
        ),
    ]
