# Generated by Django 5.2.1 on 2025-10-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='job_function',
        ),
    ]
