# Generated by Django 5.2.1 on 2025-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_evaluationscale_evaluationtargetconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentobjective',
            name='performance_year',
        ),
    ]
