# Generated by Django 5.2.1 on 2025-10-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_departmentobjective_performance_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeperformance',
            old_name='objectives_set_date',
            new_name='competencies_submitted_date',
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='competencies_draft_saved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='competencies_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='development_needs_draft_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='development_needs_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='end_year_employee_draft_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='end_year_manager_draft_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='mid_year_employee_draft_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='mid_year_manager_draft_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='objectives_draft_saved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='objectives_employee_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='objectives_employee_submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='objectives_manager_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscale',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objectivestatus',
            name='value',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
