# Generated by Django 5.2.1 on 2025-10-27 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_rename_objectives_set_date_employeeperformance_competencies_submitted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecompetencyrating',
            options={'ordering': ['behavioral_competency__group', 'behavioral_competency__name']},
        ),
        migrations.AlterUniqueTogether(
            name='employeecompetencyrating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='total_competencies_score',
        ),
        migrations.RemoveField(
            model_name='evaluationtargetconfig',
            name='competency_score_target',
        ),
        migrations.AddField(
            model_name='employeecompetencyrating',
            name='behavioral_competency',
            field=models.ForeignKey(blank=True, help_text='Behavioral competency from competency framework', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.behavioralcompetency'),
        ),
        migrations.AddField(
            model_name='employeecompetencyrating',
            name='required_level',
            field=models.IntegerField(blank=True, help_text='Required level from position behavioral assessment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='competencies_letter_grade',
            field=models.CharField(blank=True, help_text='Letter grade based on percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='group_competency_scores',
            field=models.JSONField(default=dict, help_text='Scores by behavioral competency group: {group_name: {required, actual, percentage, letter_grade}}'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='total_competencies_actual_score',
            field=models.IntegerField(default=0, help_text='Total actual behavioral competency score'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='total_competencies_required_score',
            field=models.IntegerField(default=0, help_text='Total required behavioral competency score from position assessment'),
        ),
        migrations.AlterField(
            model_name='developmentneed',
            name='competency_gap',
            field=models.CharField(help_text='Behavioral competency name with gap', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeecompetencyrating',
            name='end_year_rating',
            field=models.ForeignKey(blank=True, help_text='Actual rating using Evaluation Scale (E++, E+, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_ratings', to='api.evaluationscale'),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='competencies_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(actual/required) * 100', max_digits=5),
        ),
        migrations.AlterField(
            model_name='performanceweightconfig',
            name='competencies_weight',
            field=models.IntegerField(help_text='Behavioral Competencies weight percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RemoveField(
            model_name='employeecompetencyrating',
            name='competency',
        ),
    ]
