# Generated by Django 5.2.1 on 2025-10-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_employeecompetencyrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceyear',
            name='sequential_mode',
            field=models.BooleanField(default=False, help_text='Enable sequential mode - allows all periods on same dates, processes happen based on status'),
        ),
    ]
