# Generated by Django 5.2.1 on 2025-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_performanceyear_sequential_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceyear',
            name='sequential_mode',
            field=models.BooleanField(default=True, help_text='Enable sequential mode - allows all periods on same dates, processes happen based on status'),
        ),
    ]
