# Generated by Django 5.2.1 on 2025-10-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_alter_performanceyear_sequential_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceyear',
            name='sequential_mode',
        ),
    ]
