# Generated by Django 5.2.1 on 2025-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_remove_performanceyear_sequential_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentobjective',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
