# Generated by Django 5.2.1 on 2025-10-30 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_departmentobjective_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipCompetencyChildGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_leadership_child_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipCompetencyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.leadershipcompetencychildgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_leadership_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipCompetencyMainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_leadership_main_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leadershipcompetencychildgroup',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='api.leadershipcompetencymaingroup'),
        ),
        migrations.AlterUniqueTogether(
            name='leadershipcompetencychildgroup',
            unique_together={('main_group', 'name')},
        ),
    ]
