# Generated by Django 5.2.1 on 2025-10-30 07:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_leadershipcompetencychildgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLeadershipAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('grade_levels', models.JSONField(default=list, help_text='List of grade levels for this position')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position_group', models.ForeignKey(help_text='Only Manager, Vice Chairman, Director, Vice, HOD positions', on_delete=django.db.models.deletion.CASCADE, to='api.positiongroup')),
            ],
            options={
                'db_table': 'position_leadership_assessments',
                'unique_together': {('position_group', 'job_title')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeadershipAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('main_group_scores', models.JSONField(default=dict, help_text='Scores by main leadership group: {main_group_name: {position_total, employee_total, percentage, letter_grade, child_groups: {...}}}')),
                ('child_group_scores', models.JSONField(default=dict, help_text='Scores by child leadership group: {child_group_name: {position_total, employee_total, percentage, letter_grade}}')),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_letter_grade', models.CharField(default='N/A', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assessments', to='api.employee')),
                ('position_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.positionleadershipassessment')),
            ],
            options={
                'db_table': 'employee_leadership_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeadershipCompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('actual_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='api.employeeleadershipassessment')),
                ('leadership_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leadershipcompetencyitem')),
            ],
            options={
                'db_table': 'employee_leadership_ratings',
                'unique_together': {('assessment', 'leadership_item')},
            },
        ),
        migrations.CreateModel(
            name='PositionLeadershipCompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(help_text='Required leadership competency level for this position', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leadership_item', models.ForeignKey(help_text='Specific leadership competency item', on_delete=django.db.models.deletion.CASCADE, to='api.leadershipcompetencyitem')),
                ('position_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='api.positionleadershipassessment')),
            ],
            options={
                'db_table': 'position_leadership_ratings',
                'unique_together': {('position_assessment', 'leadership_item')},
            },
        ),
    ]
