# Generated by Django 5.2.1 on 2025-10-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_positionleadershipassessment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionbehavioralassessment',
            unique_together={('position_group',)},
        ),
        migrations.AlterUniqueTogether(
            name='positionleadershipassessment',
            unique_together={('position_group',)},
        ),
        migrations.RemoveField(
            model_name='positionbehavioralassessment',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='positionleadershipassessment',
            name='job_title',
        ),
    ]
