# Generated by Django 5.2.1 on 2025-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_alter_positionbehavioralassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecoreassessment',
            name='group_scores',
            field=models.JSONField(default=dict, help_text='Scores by skill group: {group_name: {position_total, employee_total, gap, completion_percentage}}'),
        ),
    ]
