# Generated by Django 5.2.1 on 2025-11-04 07:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_employeecoreassessment_group_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monthly_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Default aylıq icazə saatı', max_digits=5)),
                ('max_request_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Bir request-də maksimum saat', max_digits=4)),
                ('min_advance_hours', models.IntegerField(default=24, help_text='Neçə saat əvvəldən sorğu göndərmək lazımdır')),
                ('hr_notification_emails', models.TextField(default='hr@almettrading.com', help_text='HR email-ləri (vergüllə ayrılmış)')),
                ('enable_auto_approval', models.BooleanField(default=False, help_text='Avtomatik approve (testing üçün)')),
                ('is_active', models.BooleanField(default=True, help_text='Sistem aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Off Settings',
                'verbose_name_plural': 'Time Off Settings',
                'db_table': 'timeoff_settings',
            },
        ),
        migrations.CreateModel(
            name='TimeOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_allowance_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Aylıq icazə saatı (default: 4 saat)', max_digits=5)),
                ('current_balance_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Cari balans (saat)', max_digits=6)),
                ('used_hours_this_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Bu ay istifadə olunan saat', max_digits=5)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Son reset tarixi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_balance', to='api.employee')),
            ],
            options={
                'verbose_name': 'Time Off Balance',
                'verbose_name_plural': 'Time Off Balances',
                'db_table': 'timeoff_balances',
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='İcazə tarixi')),
                ('start_time', models.TimeField(help_text='Başlama saatı')),
                ('end_time', models.TimeField(help_text='Bitmə saatı')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Müddət (saat)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8)])),
                ('reason', models.TextField(help_text='İcazə səbəbi')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Line Manager Approval'), ('APPROVED', 'Approved by Line Manager'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Employee')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('balance_deducted', models.BooleanField(default=False, help_text='Balansdan çıxarılıb?')),
                ('hr_notified', models.BooleanField(default=False, help_text='HR-lara bildiriş göndərilib?')),
                ('hr_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timeoff_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeoff_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_requests', to='api.employee')),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeoff_requests_to_approve', to='api.employee')),
            ],
            options={
                'verbose_name': 'Time Off Request',
                'verbose_name_plural': 'Time Off Requests',
                'db_table': 'timeoff_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Request Created'), ('APPROVED', 'Approved by Manager'), ('REJECTED', 'Rejected by Manager'), ('CANCELLED', 'Cancelled by Employee'), ('HR_NOTIFIED', 'HR Notified'), ('BALANCE_UPDATED', 'Balance Updated')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.timeoffrequest')),
            ],
            options={
                'verbose_name': 'Time Off Activity',
                'verbose_name_plural': 'Time Off Activities',
                'db_table': 'timeoff_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['employee', 'status'], name='timeoff_req_employe_0e04fc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['date'], name='timeoff_req_date_ae9598_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['status', '-created_at'], name='timeoff_req_status_8d0bc5_idx'),
        ),
    ]
