# Generated by Django 5.2.1 on 2025-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_timeoffsettings_timeoffbalance_timeoffrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='timeoff_subject_prefix',
            field=models.CharField(default='[TIME OFF]', help_text='Subject prefix for time off emails', max_length=50),
        ),
    ]
