# Generated by Django 5.2.1 on 2025-11-06 13:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_notificationsettings_timeoff_subject_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecompetencyrating',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='employeecompetencyrating',
            name='leadership_item',
            field=models.ForeignKey(blank=True, help_text='Leadership competency item for senior positions', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.leadershipcompetencyitem'),
        ),
        migrations.AlterField(
            model_name='employeecompetencyrating',
            name='required_level',
            field=models.IntegerField(blank=True, help_text='Required level from position assessment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
