# Generated by Django 5.2.1 on 2025-11-13 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_alter_employeecompetencyrating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kateqoriya adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Policy Kateqoriyası',
                'verbose_name_plural': 'Policy Kateqoriyaları',
                'db_table': 'policy_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='name',
            field=models.CharField(choices=[('VC', 'Vice Chairman'), ('Chairman', 'Chairman'), ('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('HEAD OF DEPARTMENT', 'Head of Department'), ('SENIOR SPECIALIST', 'Senior Specialist'), ('SPECIALIST', 'Specialist'), ('JUNIOR SPECIALIST', 'Junior Specialist'), ('BLUE COLLAR', 'Blue Collar')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('pdf_file', models.FileField(help_text='PDF formatında olmalıdır', upload_to='policies/pdfs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Fayl')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiya')),
                ('effective_date', models.DateField(help_text='Policy-nin qüvvəyə minmə tarixi', verbose_name='Qüvvəyə minmə tarixi')),
                ('review_date', models.DateField(blank=True, help_text='Növbəti baxış tarixi', null=True, verbose_name='Baxış tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Bütün əməkdaşlar üçün məcburidirmi?', verbose_name='Məcburi')),
                ('download_count', models.IntegerField(default=0, verbose_name='Yükləmə sayı')),
                ('view_count', models.IntegerField(default=0, verbose_name='Baxış sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL, verbose_name='Yeniləyən')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='api.policycategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Şirkət Policy-si',
                'verbose_name_plural': 'Şirkət Policy-ləri',
                'db_table': 'company_policies',
                'ordering': ['category__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Təsdiq tarixi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to=settings.AUTH_USER_MODEL, verbose_name='Əməkdaş')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='api.companypolicy', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Policy Təsdiqi',
                'verbose_name_plural': 'Policy Təsdiqləri',
                'db_table': 'policy_acknowledgments',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('policy', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['category', 'is_active'], name='company_pol_categor_8960d1_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['slug'], name='company_pol_slug_4afb8c_idx'),
        ),
    ]
