# Generated by Django 5.2.1 on 2025-11-17 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_policycategory_alter_positiongroup_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('PRINT', 'Printed')], default='VIEW', help_text='Type of access action', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, help_text='When the access occurred')),
            ],
            options={
                'verbose_name': 'Policy Access Log',
                'verbose_name_plural': 'Policy Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Folder name (e.g., 'Employment Lifecycle', 'Legal & Compliance')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this folder contains')),
                ('icon', models.CharField(default='📁', help_text='Emoji icon for the folder (e.g., 👥, ⚖️, 🎁)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order within business function (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this folder is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Folder',
                'verbose_name_plural': 'Policy Folders',
                'ordering': ['business_function', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., 1.0, 1.1, 2.0)', max_length=20)),
                ('policy_file', models.FileField(help_text='Previous version of the policy file', upload_to='company_policies/versions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('changes_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
            ],
            options={
                'verbose_name': 'Policy Version',
                'verbose_name_plural': 'Policy Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='companypolicy',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Company Policy', 'verbose_name_plural': 'Company Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyacknowledgment',
            options={'ordering': ['-acknowledged_at'], 'verbose_name': 'Policy Acknowledgment', 'verbose_name_plural': 'Policy Acknowledgments'},
        ),
        migrations.RemoveIndex(
            model_name='companypolicy',
            name='company_pol_categor_8960d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='companypolicy',
            name='company_pol_slug_4afb8c_idx',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='slug',
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this policy was approved', null=True),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time this policy was accessed', null=True),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='policy_file',
            field=models.FileField(default=1, help_text='Policy document (PDF only, max 10MB)', upload_to='company_policies/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='requires_acknowledgment',
            field=models.BooleanField(default=False, help_text='Do employees need to acknowledge reading this policy?'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current status of the policy', max_length=20),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the policy'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this policy has been downloaded'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when policy becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this policy is active and visible'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Is this policy mandatory for all employees?'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='review_date',
            field=models.DateField(blank=True, help_text='Next review date for this policy', null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='title',
            field=models.CharField(help_text="Policy title (e.g., 'Hiring Procedure', 'Vacation Policy')", max_length=300),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='version',
            field=models.CharField(default='1.0', help_text='Policy version (e.g., 1.0, 1.1, 2.0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this policy has been viewed'),
        ),
        migrations.AlterField(
            model_name='policyacknowledgment',
            name='acknowledged_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the acknowledgment was made'),
        ),
        migrations.AlterField(
            model_name='policyacknowledgment',
            name='employee',
            field=models.ForeignKey(help_text='Employee who acknowledged the policy', on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='policyacknowledgment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which acknowledgment was made', null=True),
        ),
        migrations.AlterField(
            model_name='policyacknowledgment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments from employee'),
        ),
        migrations.AlterField(
            model_name='policyacknowledgment',
            name='policy',
            field=models.ForeignKey(help_text='Policy that was acknowledged', on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='api.companypolicy'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['policy', 'employee'], name='api_policya_policy__644037_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['-acknowledged_at'], name='api_policya_acknowl_e5b1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['policy', '-acknowledged_at'], name='api_policya_policy__b22baf_idx'),
        ),
        migrations.AlterModelTable(
            name='companypolicy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='policyacknowledgment',
            table=None,
        ),
        migrations.AddField(
            model_name='policyaccesslog',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who accessed the policy (if linked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_access_logs', to='api.employee'),
        ),
        migrations.AddField(
            model_name='policyaccesslog',
            name='policy',
            field=models.ForeignKey(help_text='Policy that was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.companypolicy'),
        ),
        migrations.AddField(
            model_name='policyaccesslog',
            name='user',
            field=models.ForeignKey(help_text='Django user who accessed the policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyfolder',
            name='business_function',
            field=models.ForeignKey(help_text='Business function this folder belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policy_folders', to='api.businessfunction'),
        ),
        migrations.AddField(
            model_name='policyfolder',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='folder',
            field=models.ForeignKey(default=1, help_text='Folder this policy belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='api.policyfolder'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['folder', 'is_active'], name='api_company_folder__888d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['status'], name='api_company_status_c34fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['effective_date'], name='api_company_effecti_0ce3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['-updated_at'], name='api_company_updated_faea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['is_mandatory'], name='api_company_is_mand_0b1aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='companypolicy',
            index=models.Index(fields=['requires_acknowledgment'], name='api_company_require_42eae9_idx'),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='policy',
            field=models.ForeignKey(help_text='Policy this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='api.companypolicy'),
        ),
        migrations.DeleteModel(
            name='PolicyCategory',
        ),
        migrations.AddIndex(
            model_name='policyaccesslog',
            index=models.Index(fields=['policy', '-accessed_at'], name='api_policya_policy__6c490d_idx'),
        ),
        migrations.AddIndex(
            model_name='policyaccesslog',
            index=models.Index(fields=['user', '-accessed_at'], name='api_policya_user_id_8f74e7_idx'),
        ),
        migrations.AddIndex(
            model_name='policyaccesslog',
            index=models.Index(fields=['employee', '-accessed_at'], name='api_policya_employe_cca4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='policyaccesslog',
            index=models.Index(fields=['-accessed_at'], name='api_policya_accesse_8dbcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='policyaccesslog',
            index=models.Index(fields=['action'], name='api_policya_action_e10c73_idx'),
        ),
        migrations.AddIndex(
            model_name='policyfolder',
            index=models.Index(fields=['business_function', 'is_active'], name='api_policyf_busines_8198fa_idx'),
        ),
        migrations.AddIndex(
            model_name='policyfolder',
            index=models.Index(fields=['order'], name='api_policyf_order_7f57d4_idx'),
        ),
        migrations.AddIndex(
            model_name='policyfolder',
            index=models.Index(fields=['created_at'], name='api_policyf_created_c65dfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyfolder',
            unique_together={('business_function', 'name')},
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy', '-created_at'], name='api_policyv_policy__86dfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['-created_at'], name='api_policyv_created_25181e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('policy', 'version')},
        ),
    ]
