# Generated by Django 5.2.1 on 2025-11-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_policyaccesslog_policyfolder_policyversion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyAccessLog',
        ),
    ]
