# Generated by Django 5.2.1 on 2025-11-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_delete_policyaccesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypolicy',
            name='version',
        ),
        migrations.DeleteModel(
            name='PolicyVersion',
        ),
    ]
