# Generated by Django 5.2.1 on 2025-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_remove_companypolicy_version_delete_policyversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyfolder',
            options={'ordering': ['business_function', 'name'], 'verbose_name': 'Policy Folder', 'verbose_name_plural': 'Policy Folders'},
        ),
        migrations.RemoveIndex(
            model_name='policyfolder',
            name='api_policyf_order_7f57d4_idx',
        ),
        migrations.RemoveField(
            model_name='policyfolder',
            name='order',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='grading_levels',
            field=models.JSONField(default=list, help_text="List of grading levels (e.g., ['M', 'N', 'O'])"),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use grading_levels instead. Kept for backward compatibility.', max_length=50, null=True),
        ),
    ]
