# Generated by Django 5.2.1 on 2025-11-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_alter_policyfolder_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companypolicy',
            name='api_company_status_c34fe5_idx',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='status',
        ),
    ]
