# Generated by Django 5.2.1 on 2025-11-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_remove_companypolicy_api_company_status_c34fe5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companypolicy',
            name='api_company_effecti_0ce3d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='companypolicy',
            name='api_company_is_mand_0b1aa7_idx',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='companypolicy',
            name='review_date',
        ),
    ]
