# Generated by Django 5.2.1 on 2025-11-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_remove_companypolicy_api_company_effecti_0ce3d7_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescriptionActivity',
        ),
    ]
