# Generated by Django 5.2.1 on 2025-11-18 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_delete_jobdescriptionactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_approved_at',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_approved_by',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_comments',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_signature',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_approved_at',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_approved_by',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_comments',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_signature',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='status',
        ),
        migrations.AlterField(
            model_name='accessmatrixitem',
            name='access_matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.accessmatrix'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.companybenefit'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobbusinessresourceitem',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.jobbusinessresource'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use grading_levels instead.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescriptionaccessmatrix',
            name='specific_items',
            field=models.ManyToManyField(blank=True, related_name='job_descriptions', to='api.accessmatrixitem'),
        ),
        migrations.AlterField(
            model_name='jobdescriptionbusinessresource',
            name='specific_items',
            field=models.ManyToManyField(blank=True, related_name='job_descriptions', to='api.jobbusinessresourceitem'),
        ),
        migrations.AlterField(
            model_name='jobdescriptioncompanybenefit',
            name='specific_items',
            field=models.ManyToManyField(blank=True, related_name='job_descriptions', to='api.companybenefititem'),
        ),
        migrations.CreateModel(
            name='JobDescriptionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VACANCY', 'Vacant Position')], default='EMPLOYEE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_LINE_MANAGER', 'Pending Line Manager Approval'), ('PENDING_EMPLOYEE', 'Pending Employee Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', max_length=25)),
                ('line_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('line_manager_comments', models.TextField(blank=True)),
                ('line_manager_signature', models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/line_managers/')),
                ('employee_approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('employee_signature', models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/employees/')),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_reason', models.CharField(blank=True, help_text="Reason for deactivation (e.g., 'Employee deleted', 'Vacancy filled')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_assignments', to='api.employee', verbose_name='Assigned Employee')),
                ('employee_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_approved_jd_assignments', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.jobdescription', verbose_name='Job Description')),
                ('line_manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm_approved_jd_assignments', to=settings.AUTH_USER_MODEL)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_jd_assignments', to='api.employee', verbose_name='Reports To')),
                ('vacant_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_assignments', to='api.vacantposition', verbose_name='Vacant Position')),
            ],
            options={
                'verbose_name': 'Job Description Assignment',
                'verbose_name_plural': 'Job Description Assignments',
                'db_table': 'job_description_assignments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('is_active', True)), fields=('job_description', 'employee'), name='unique_active_employee_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('vacant_position__isnull', False)), fields=('job_description', 'vacant_position'), name='unique_active_vacancy_assignment')],
            },
        ),
    ]
