# Generated by Django 5.2.1 on 2025-11-18 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_remove_jobdescription_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_descriptions', to='api.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employee_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employee_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_approved_job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employee_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employee_signature',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/employees/'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='line_manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='line_manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_manager_approved_job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='line_manager_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='line_manager_signature',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/line_managers/'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_job_descriptions', to='api.employee', verbose_name='Reports To'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_LINE_MANAGER', 'Pending Line Manager Approval'), ('PENDING_EMPLOYEE', 'Pending Employee Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='accessmatrixitem',
            name='access_matrix',
            field=models.ForeignKey(help_text='Parent access category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.accessmatrix'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='benefit',
            field=models.ForeignKey(help_text='Parent benefit category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.companybenefit'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details like eligibility, conditions, etc.'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='value',
            field=models.CharField(blank=True, help_text="Benefit value (e.g., '21 days', '100%', '£500')", max_length=100),
        ),
        migrations.AlterField(
            model_name='jobbusinessresourceitem',
            name='resource',
            field=models.ForeignKey(help_text='Parent resource category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.jobbusinessresource'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use grading_levels instead. Kept for backward compatibility.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescriptionaccessmatrix',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific access rights required', related_name='job_descriptions', to='api.accessmatrixitem'),
        ),
        migrations.AlterField(
            model_name='jobdescriptionbusinessresource',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific items required (leave empty for any)', related_name='job_descriptions', to='api.jobbusinessresourceitem'),
        ),
        migrations.AlterField(
            model_name='jobdescriptioncompanybenefit',
            name='specific_items',
            field=models.ManyToManyField(blank=True, help_text='Specific benefit details', related_name='job_descriptions', to='api.companybenefititem'),
        ),
        migrations.DeleteModel(
            name='JobDescriptionAssignment',
        ),
    ]
