# Generated by Django 5.2.1 on 2025-11-19 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_jobdescription_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_approved_at',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_approved_by',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_comments',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='employee_signature',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_approved_at',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_approved_by',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_comments',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='line_manager_signature',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='status',
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details'),
        ),
        migrations.AlterField(
            model_name='companybenefititem',
            name='value',
            field=models.CharField(blank=True, help_text="Benefit value (e.g., '21 days', '100%')", max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='grading_level',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use grading_levels instead.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='JobDescriptionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_vacancy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_LINE_MANAGER', 'Pending Line Manager Approval'), ('PENDING_EMPLOYEE', 'Pending Employee Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', max_length=25)),
                ('line_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('line_manager_comments', models.TextField(blank=True)),
                ('employee_approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('line_manager_signature', models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/line_managers/')),
                ('employee_signature', models.FileField(blank=True, null=True, upload_to='job_descriptions/signatures/employees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_removed_at', models.DateTimeField(blank=True, null=True)),
                ('employee_removed_reason', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_description_assignments', to='api.employee')),
                ('employee_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.jobdescription')),
                ('line_manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm_approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_assignments', to='api.employee')),
                ('vacancy_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_description_assignments', to='api.vacantposition')),
            ],
            options={
                'verbose_name': 'Job Description Assignment',
                'verbose_name_plural': 'Job Description Assignments',
                'db_table': 'job_description_assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
