# Generated by Django 5.2.1 on 2025-11-24 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_celebration_celebrationimage_celebrationwish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='company_news_sender_email',
            field=models.EmailField(default='myalmet@almettrading.com', help_text='Email address for sending company news (must be valid Outlook/Exchange mailbox)', max_length=254),
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Category',
                'verbose_name_plural': 'Training Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('training_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('training_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional'), ('ROLE_BASED', 'Role Based')], default='OPTIONAL', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, help_text='Estimated duration in hours', max_digits=5)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_completion', models.BooleanField(default=False)),
                ('completion_deadline_days', models.IntegerField(blank=True, help_text='Days after assignment to complete', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_functions', models.ManyToManyField(blank=True, help_text='Specific business functions for this training', to='api.businessfunction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, help_text='Specific departments for this training', to='api.department')),
                ('position_groups', models.ManyToManyField(blank=True, help_text='Specific position groups for this training', to='api.positiongroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='api.trainingcategory')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('PRESENTATION', 'Presentation'), ('DOCUMENT', 'Document'), ('LINK', 'External Link'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload file for PDF, Video, etc.', null=True, upload_to='training_materials/%Y/%m/')),
                ('external_link', models.URLField(blank=True, help_text='External link for online resources', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='For videos', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Must be viewed to complete training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.training')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Material',
                'verbose_name_plural': 'Training Materials',
                'ordering': ['training', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Completion progress 0-100', max_digits=5)),
                ('completion_notes', models.TextField(blank=True)),
                ('completion_certificate_generated', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Is this assignment mandatory for the employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='api.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.training')),
                ('materials_completed', models.ManyToManyField(blank=True, help_text='Materials that have been viewed/completed', to='api.trainingmaterial')),
            ],
            options={
                'verbose_name': 'Training Assignment',
                'verbose_name_plural': 'Training Assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('training', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='TrainingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ASSIGNED', 'Training Assigned'), ('STARTED', 'Training Started'), ('MATERIAL_VIEWED', 'Material Viewed'), ('PROGRESS_UPDATED', 'Progress Updated'), ('COMPLETED', 'Training Completed'), ('CANCELLED', 'Training Cancelled')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.trainingassignment')),
                ('material', models.ForeignKey(blank=True, help_text='Related material if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainingmaterial')),
            ],
            options={
                'verbose_name': 'Training Activity',
                'verbose_name_plural': 'Training Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
