# Generated by Django 5.2.1 on 2025-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_alter_notificationsettings_company_news_sender_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contracttypeconfig',
            name='onboarding_days',
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PROBATION', 'Probation'), ('VACANT', 'Vacant Position')], default='ACTIVE', max_length=20),
        ),
        migrations.DeleteModel(
            name='TrainingCategory',
        ),
    ]
