# Generated by Django 5.2.1 on 2025-11-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_remove_training_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created_at'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='training',
            name='estimated_duration_hours',
        ),
        migrations.RemoveField(
            model_name='training',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_type',
        ),
    ]
