# Generated by Django 5.2.1 on 2025-11-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_alter_training_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='title',
        ),
    ]
