# Generated by Django 5.2.1 on 2025-11-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_remove_trainingmaterial_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='external_link',
        ),
    ]
