# Generated by Django 5.2.1 on 2025-12-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_handoverrequest_handoverimportantdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
