# Generated by Django 5.2.1 on 2025-12-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_delete_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeobjective',
            name='progress',
        ),
    ]
