# Generated by Django 5.2.1 on 2025-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_remove_employeeobjective_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverrequest',
            name='access_info',
            field=models.TextField(blank=True, help_text='System access information, usernames, password locations'),
        ),
        migrations.AlterField(
            model_name='handoverrequest',
            name='contacts',
            field=models.TextField(blank=True, help_text='Related contacts with their roles and contact information'),
        ),
        migrations.AlterField(
            model_name='handoverrequest',
            name='documents_info',
            field=models.TextField(blank=True, help_text='Document and file locations, shared drives'),
        ),
        migrations.AlterField(
            model_name='handoverrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes, tips, recommendations'),
        ),
        migrations.AlterField(
            model_name='handoverrequest',
            name='open_issues',
            field=models.TextField(blank=True, help_text='Unresolved problems, pending actions, known issues'),
        ),
        migrations.AlterField(
            model_name='handovertask',
            name='current_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('POSTPONED', 'Postponed')], default='NOT_STARTED', max_length=20),
        ),
    ]
