# Generated by Django 5.2.1 on 2025-12-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_alter_handoverrequest_access_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverattachment',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='handovertype',
            name='description',
        ),
    ]
