# Generated by Django 5.2.1 on 2026-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_remove_handoverattachment_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='handover_sender_email',
            field=models.EmailField(default='myalmet@almettrading.com', help_text='Email address for sending handover notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='handover_subject_prefix',
            field=models.CharField(default='[HANDOVER]', help_text='Subject prefix for handover emails', max_length=50),
        ),
    ]
