# Generated by Django 5.2.1 on 2026-01-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_notificationsettings_handover_sender_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyfolder',
            options={'ordering': ['name'], 'verbose_name': 'Policy Folder', 'verbose_name_plural': 'Policy Folders'},
        ),
        migrations.AlterUniqueTogether(
            name='policyfolder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='policyfolder',
            name='business_function',
            field=models.ForeignKey(blank=True, help_text='Business function this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_folders', to='api.businessfunction'),
        ),
        migrations.AlterField(
            model_name='policyfolder',
            name='icon',
            field=models.CharField(default='📁', help_text='Emoji icon for the folder', max_length=10),
        ),
        migrations.CreateModel(
            name='PolicyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company name (e.g., 'External Partner', 'Client Company')", max_length=200, unique=True)),
                ('code', models.CharField(help_text="Company code (e.g., 'EXT', 'CLIENT')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the company')),
                ('icon', models.CharField(default='🏢', help_text='Emoji icon for the company', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Company',
                'verbose_name_plural': 'Policy Companies',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='policyfolder',
            name='policy_company',
            field=models.ForeignKey(blank=True, help_text='Manual company this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_folders', to='api.policycompany'),
        ),
        migrations.AddIndex(
            model_name='policyfolder',
            index=models.Index(fields=['policy_company', 'is_active'], name='api_policyf_policy__71b0df_idx'),
        ),
        migrations.AddIndex(
            model_name='policycompany',
            index=models.Index(fields=['code'], name='api_policyc_code_29424b_idx'),
        ),
        migrations.AddIndex(
            model_name='policycompany',
            index=models.Index(fields=['is_active'], name='api_policyc_is_acti_af353d_idx'),
        ),
    ]
