# Generated by Django 5.2.1 on 2026-01-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_alter_policyfolder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycompany',
            options={'ordering': ['name'], 'verbose_name': 'Policy Company', 'verbose_name_plural': 'Policy Companies'},
        ),
        migrations.RemoveIndex(
            model_name='policycompany',
            name='api_policyc_code_29424b_idx',
        ),
        migrations.RemoveField(
            model_name='policycompany',
            name='code',
        ),
        migrations.RemoveField(
            model_name='policycompany',
            name='description',
        ),
    ]
