# Generated by Django 5.2.1 on 2026-01-05 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_alter_policycompany_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycompany',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Policy Company', 'verbose_name_plural': 'Policy Companies'},
        ),
        migrations.AddField(
            model_name='policycompany',
            name='code',
            field=models.CharField(default='', help_text="Company code (e.g., 'EXT', 'CLIENT')", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policycompany',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the company'),
        ),
        migrations.AddIndex(
            model_name='policycompany',
            index=models.Index(fields=['code'], name='api_policyc_code_29424b_idx'),
        ),
    ]
