# Generated by Django 5.2.1 on 2026-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_alter_policycompany_options_policycompany_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffbalance',
            name='is_initialized',
            field=models.BooleanField(default=False, help_text='Balance initialized by admin?'),
        ),
        migrations.AlterField(
            model_name='timeoffbalance',
            name='current_balance_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cari balans (saat)', max_digits=6),
        ),
    ]
