# Generated by Django 5.2.1 on 2026-01-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_timeoffbalance_is_initialized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffactivity',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.timeoffrequest'),
        ),
    ]
