# Generated by Django 5.2.1 on 2026-01-08 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_alter_timeoffactivity_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., H1 2024, H2 2024', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Only one period can be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed by Manager')], default='DRAFT', max_length=20)),
                ('overall_core_skills_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_behavioral_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_leadership_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to='api.employee')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to='api.assessmentperiod')),
            ],
            options={
                'db_table': 'self_assessments',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Assessment Created'), ('UPDATED', 'Assessment Updated'), ('SUBMITTED', 'Assessment Submitted'), ('REVIEWED', 'Reviewed by Manager'), ('RATING_CHANGED', 'Rating Changed')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.selfassessment')),
            ],
            options={
                'db_table': 'assessment_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipCompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comment', models.TextField(blank=True, help_text="Employee's self-reflection")),
                ('manager_comment', models.TextField(blank=True, help_text="Manager's feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leadershipcompetencyitem')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_ratings', to='api.selfassessment')),
            ],
            options={
                'db_table': 'leadership_competency_ratings',
                'unique_together': {('assessment', 'competency_item')},
            },
        ),
        migrations.CreateModel(
            name='CoreSkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comment', models.TextField(blank=True, help_text="Employee's self-reflection")),
                ('manager_comment', models.TextField(blank=True, help_text="Manager's feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_skill_ratings', to='api.selfassessment')),
            ],
            options={
                'db_table': 'core_skill_ratings',
                'unique_together': {('assessment', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='BehavioralCompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comment', models.TextField(blank=True, help_text="Employee's self-reflection")),
                ('manager_comment', models.TextField(blank=True, help_text="Manager's feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.behavioralcompetency')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_ratings', to='api.selfassessment')),
            ],
            options={
                'db_table': 'behavioral_competency_ratings',
                'unique_together': {('assessment', 'competency')},
            },
        ),
    ]
