# Generated by Django 5.2.1 on 2026-01-08 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_assessmentperiod_selfassessment_assessmentactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coreskillrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coreskillrating',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='coreskillrating',
            name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='leadershipcompetencyrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leadershipcompetencyrating',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='leadershipcompetencyrating',
            name='competency_item',
        ),
        migrations.AlterModelOptions(
            name='assessmentactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Assessment Activities'},
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='overall_behavioral_score',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='overall_core_skills_score',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='overall_leadership_score',
        ),
        migrations.AlterField(
            model_name='assessmentactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentperiod',
            name='name',
            field=models.CharField(help_text='e.g., H1 2025, H2 2025', max_length=200),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='manager_comments',
            field=models.TextField(blank=True, help_text='Overall manager feedback'),
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of all skill ratings', max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='SkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1 (Basic) to 5 (Expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_comment', models.TextField(blank=True, help_text="Employee's self-reflection on this skill")),
                ('manager_comment', models.TextField(blank=True, help_text="Manager's feedback on this skill rating")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to='api.selfassessment')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'skill_ratings',
                'ordering': ['skill__group__name', 'skill__name'],
                'unique_together': {('assessment', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='BehavioralCompetencyRating',
        ),
        migrations.DeleteModel(
            name='CoreSkillRating',
        ),
        migrations.DeleteModel(
            name='LeadershipCompetencyRating',
        ),
    ]
