# Generated by Django 5.2.1 on 2026-01-09 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_alter_coreskillrating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company name (e.g., 'External Partner', 'Client Company')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the company')),
                ('icon', models.CharField(default='🏢', help_text='Emoji icon for the company', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedure_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedure Company',
                'verbose_name_plural': 'Procedure Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Folder name (e.g., 'Operations', 'Quality Control')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this folder contains')),
                ('icon', models.CharField(default='📋', help_text='Emoji icon for the folder', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this folder is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_function', models.ForeignKey(blank=True, help_text='Business function this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_folders', to='api.businessfunction')),
                ('created_by', models.ForeignKey(help_text='User who created this folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedure_folders', to=settings.AUTH_USER_MODEL)),
                ('procedure_company', models.ForeignKey(blank=True, help_text='Manual company this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_folders', to='api.procedurecompany')),
            ],
            options={
                'verbose_name': 'Procedure Folder',
                'verbose_name_plural': 'Procedure Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Procedure title (e.g., 'Purchase Request Process', 'Quality Check')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Brief description of the procedure')),
                ('procedure_file', models.FileField(help_text='Procedure document (PDF only, max 10MB)', upload_to='company_procedures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes (auto-calculated)', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this procedure has been downloaded')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this procedure has been viewed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this procedure is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this procedure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedures', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this procedure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_procedures', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(help_text='Folder this procedure belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='api.procedurefolder')),
            ],
            options={
                'verbose_name': 'Company Procedure',
                'verbose_name_plural': 'Company Procedures',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='procedurecompany',
            index=models.Index(fields=['name'], name='api_procedu_name_d92047_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurecompany',
            index=models.Index(fields=['is_active'], name='api_procedu_is_acti_c840d9_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurefolder',
            index=models.Index(fields=['business_function', 'is_active'], name='api_procedu_busines_86e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurefolder',
            index=models.Index(fields=['procedure_company', 'is_active'], name='api_procedu_procedu_b0b5de_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurefolder',
            index=models.Index(fields=['created_at'], name='api_procedu_created_a5f6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprocedure',
            index=models.Index(fields=['folder', 'is_active'], name='api_company_folder__ed8c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprocedure',
            index=models.Index(fields=['-updated_at'], name='api_company_updated_81efdc_idx'),
        ),
    ]
