# Generated by Django 5.2.1 on 2026-01-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_procedurecompany_procedurefolder_companyprocedure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentperiod',
            name='status',
        ),
    ]
