# Generated by Django 5.2.1 on 2026-01-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_contractrenewalrequest_exitinterview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationsetting',
            name='non_working_days',
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='half_day_end_time',
            field=models.TimeField(blank=True, help_text='Half day bitmə saatı', null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='half_day_start_time',
            field=models.TimeField(blank=True, help_text='Half day başlama saatı', null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='Half day request-dirsə True'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='uk_additional_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='uk_additional_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uk_additional_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='uk_additional_approver',
            field=models.ForeignKey(blank=True, help_text='UK: 5+ günlük requestlər üçün əlavə approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uk_additional_requests', to='api.employee'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='uk_additional_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacationsetting',
            name='non_working_days_az',
            field=models.JSONField(default=list, help_text='Azerbaijan qeyri-iş günləri JSON formatında'),
        ),
        migrations.AddField(
            model_name='vacationsetting',
            name='non_working_days_uk',
            field=models.JSONField(default=list, help_text='UK qeyri-iş günləri JSON formatında'),
        ),
        migrations.AddField(
            model_name='vacationsetting',
            name='uk_additional_approver',
            field=models.ForeignKey(blank=True, help_text='UK: 5+ günlük requestlər üçün əlavə approver (Position Group: Vice Chairman)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uk_additional_approvals', to='api.employee'),
        ),
        migrations.AddField(
            model_name='vacationtype',
            name='is_uk_only',
            field=models.BooleanField(default=False, help_text='Yalnız UK business function üçün görünən tip (məs: Half Day)'),
        ),
        migrations.AddField(
            model_name='vacationtype',
            name='requires_time_selection',
            field=models.BooleanField(default=False, help_text='Saat seçimi tələb edir (Half Day üçün)'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PENDING_LINE_MANAGER', 'Pending Line Manager'), ('PENDING_UK_ADDITIONAL', 'Pending UK Additional Approver'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED_LINE_MANAGER', 'Rejected by Line Manager'), ('REJECTED_UK_ADDITIONAL', 'Rejected by UK Additional Approver'), ('REJECTED_HR', 'Rejected by HR')], default='DRAFT', max_length=30),
        ),
    ]
