# Generated by Django 5.2.1 on 2026-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_remove_vacationsetting_non_working_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
