# Generated by Django 5.2.1 on 2026-01-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_alter_handoverrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrations', to='api.employee'),
        ),
        migrations.AddField(
            model_name='celebration',
            name='new_job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='type',
            field=models.CharField(choices=[('company_event', 'Company Event'), ('achievement', 'Achievement'), ('promotion', 'Promotion'), ('other', 'Other')], max_length=50),
        ),
    ]
