# Generated by Django 5.2.1 on 2026-01-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_celebration_employee_celebration_new_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongroup',
            name='name',
            field=models.CharField(choices=[('VC', 'Vice Chairman'), ('Chairman', 'Chairman'), ('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('C-SUITE EXECUTIVE', 'C-Suite Executive'), ('HEAD OF DEPARTMENT', 'Head of Department'), ('SENIOR SPECIALIST', 'Senior Specialist'), ('SPECIALIST', 'Specialist'), ('JUNIOR SPECIALIST', 'Junior Specialist'), ('BLUE COLLAR', 'Blue Collar')], max_length=50, unique=True),
        ),
    ]
