# Generated by Django 5.2.1 on 2026-01-21 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_objectivecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationschedule',
            options={},
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Line Manager for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_to_approve', to='api.employee'),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacationschedule',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('SCHEDULED', 'Scheduled'), ('REGISTERED', 'Registered')], default='PENDING_MANAGER', max_length=20),
        ),
        migrations.AlterModelTable(
            name='vacationschedule',
            table=None,
        ),
    ]
