# Generated by Django 5.2.1 on 2026-01-23 10:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_alter_vacationschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('initial_quantity', models.PositiveIntegerField(help_text='Başlanğıc miqdar', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_quantity', models.PositiveIntegerField(help_text='Hazırda mövcud miqdar', validators=[django.core.validators.MinValueValidator(0)])),
                ('assigned_quantity', models.PositiveIntegerField(default=0, help_text='Təyin edilmiş miqdar')),
                ('out_of_stock_quantity', models.PositiveIntegerField(default=0, help_text='Stokdan çıxarılmış miqdar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('purchase_date', models.DateField()),
                ('useful_life_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Batch',
                'verbose_name_plural': 'Asset Batches',
                'db_table': 'asset_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('transfer_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_transfer_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('total_assets', models.PositiveIntegerField(default=0)),
                ('assets_transferred', models.PositiveIntegerField(default=0)),
                ('assets_returned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_offboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetactivity',
            options={'ordering': ['-performed_at']},
        ),
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asset_n_09a21e_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_categor_840335_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_created_966918_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='asset_assig_asset_i_8ca264_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='asset_assig_employe_87ad01_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='asset_assig_check_o_cda3f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='asset_assig_check_i_da7a72_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='useful_life_years',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(default='', editable=False, help_text='Fərdi asset nömrəsi', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='out_of_stock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='out_of_stock_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(help_text='Serial nömrə (unikal)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned (Pending Approval)'), ('IN_USE', 'In Use'), ('NEED_CLARIFICATION', 'Need Clarification'), ('IN_REPAIR', 'In Repair'), ('OUT_OF_STOCK', 'Out of Stock'), ('ARCHIVED', 'Archived')], default='IN_STOCK', max_length=25),
        ),
        migrations.AlterField(
            model_name='assetactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned to Employee'), ('ACCEPTED', 'Accepted by Employee'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CLARIFICATION_PROVIDED', 'Clarification Provided'), ('CHECKED_IN', 'Checked In'), ('STATUS_CHANGED', 'Status Changed'), ('OUT_OF_STOCK', 'Marked Out of Stock'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored from Archive'), ('TRANSFERRED', 'Transferred (Offboarding)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_in_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_out_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='batch',
            field=models.ForeignKey(default=1, help_text='Bu asset hansı partiyaya aiddir', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.assetbatch'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_number'], name='assets_asset_n_43d081_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['batch'], name='assets_batch_i_2e2a34_idx'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='from_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transfers_from', to='api.employee'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='to_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transfers_to', to='api.employee'),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offboardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offboardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to='api.employee'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='offboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='api.employeeoffboarding'),
        ),
    ]
