# Generated by Django 5.2.1 on 2026-01-26 09:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_assetbatch_assettransferrequest_employeeoffboarding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransferrequest',
            name='employee_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='employee_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='it_handover_completed',
            field=models.BooleanField(default=False, help_text='IT confirmed all assets received'),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='it_handover_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='it_handover_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeoffboarding',
            name='offboarding_type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer to Another Employee'), ('RETURN', 'Return to IT (No Transfer)')], default='RETURN', help_text='Transfer or Return to IT', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(editable=False, help_text='Fərdi asset nömrəsi (auto-generated)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(help_text='Serial nömrə (manufacturer serial)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assetactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned to Employee'), ('ACCEPTED', 'Accepted by Employee'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('CLARIFICATION_PROVIDED', 'Clarification Provided'), ('CHECKED_IN', 'Checked In'), ('STATUS_CHANGED', 'Status Changed'), ('OUT_OF_STOCK', 'Marked Out of Stock'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored from Archive'), ('TRANSFERRED', 'Transferred (Offboarding)'), ('ASSIGNMENT_CANCELLED', 'Assignment Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarılma tarixi'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='check_out_date',
            field=models.DateField(verbose_name='Verilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='asset_name',
            field=models.CharField(max_length=200, verbose_name='Asset Adı'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='İşçilərə təyin edilmiş miqdar'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='available_quantity',
            field=models.PositiveIntegerField(help_text='Hələ təyin edilməmiş miqdar', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.assetcategory'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='initial_quantity',
            field=models.PositiveIntegerField(help_text='Başlanğıc miqdar (neçə ədəd alınıb)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='out_of_stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Xarab/itirilmiş miqdar'),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='total_value',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Ümumi dəyər (auto-calculated)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Hər birinin qiyməti', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='assetbatch',
            name='useful_life_years',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
